USE [master]
GO

/****** Object:  Database [FootballMatch]    Script Date: 1/18/2024 2:51:43 PM ******/
DROP DATABASE IF EXISTS [FootballMatch]
GO

/****** Object:  Database [FootballMatch]    Script Date: 1/18/2024 2:51:43 PM ******/
CREATE DATABASE [FootballMatch]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FootballMatch].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FootballMatch] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FootballMatch] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FootballMatch] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FootballMatch] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FootballMatch] SET ARITHABORT OFF 
GO

ALTER DATABASE [FootballMatch] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FootballMatch] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FootballMatch] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FootballMatch] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FootballMatch] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FootballMatch] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FootballMatch] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FootballMatch] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FootballMatch] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FootballMatch] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FootballMatch] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FootballMatch] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FootballMatch] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FootballMatch] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [FootballMatch] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FootballMatch] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [FootballMatch] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FootballMatch] SET RECOVERY FULL 
GO

ALTER DATABASE [FootballMatch] SET  MULTI_USER 
GO

ALTER DATABASE [FootballMatch] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FootballMatch] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FootballMatch] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FootballMatch] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FootballMatch] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FootballMatch] SET QUERY_STORE = OFF
GO

ALTER DATABASE [FootballMatch] SET  READ_WRITE 
GO


